name: ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: [self-hosted, nix]
    steps:
      - uses: actions/checkout@v6
        with:
          clean: false
      - uses: ./.github/actions/setup
      - run: just build

  fmt:
    runs-on: [self-hosted, nix]
    steps:
      - uses: actions/checkout@v6
        with:
          clean: false
      - uses: ./.github/actions/setup
      - run: cargo fmt --check

  clippy:
    needs: build
    runs-on: [self-hosted, nix]
    steps:
      - uses: actions/checkout@v6
        with:
          clean: false
      - uses: ./.github/actions/setup
      - run: just clippy

  unit-test:
    needs: build
    runs-on: [self-hosted, nix]
    steps:
      - uses: actions/checkout@v6
        with:
          clean: false
      - uses: ./.github/actions/setup
      - run: just unit-test

  miri:
    needs: build
    runs-on: [self-hosted, nix]
    steps:
      - uses: actions/checkout@v6
        with:
          clean: false
      - uses: ./.github/actions/setup
      - run: just miri

  system-test:
    needs: build
    runs-on: [self-hosted, nix]
    steps:
      - uses: actions/checkout@v6
        with:
          clean: false
      - uses: ./.github/actions/setup
      - run: just system-test
