name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: [self-hosted, nix]
    steps:
      - uses: actions/checkout@v6
      - uses: nicknovitski/nix-develop@v1
        with:
          arguments: ".#ci"
      - name: Run CI
        run: just ci
